name: Integration and Functional Tests

on:
  pull_request:
    branches: [ main, master, feat/* ]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create .env file
        run: |
          echo "POSTGRES_USER=${{ secrets.POSTGRES_USER || 'user' }}" >> .env
          echo "POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD || 'password' }}" >> .env
          echo "POSTGRES_DB=${{ secrets.POSTGRES_DB || 'app_db' }}" >> .env
          echo "RABBIT_USER=${{ secrets.RABBIT_USER || 'rabbit_user' }}" >> .env
          echo "RABBIT_PASS=${{ secrets.RABBIT_PASS || 'secure_password_mq' }}" >> .env

      - name: Run Tests
        env:
          DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER || 'user' }}:${{ secrets.POSTGRES_PASSWORD || 'password' }}@db:5432/${{ secrets.POSTGRES_DB || 'app_db' }}
        run: |
          docker compose --profile tests up -d db rabbitmq
          
          sleep 5
          
          docker compose --profile tests up --build --exit-code-from backend-tests backend-tests
