- name: Run Tests
        env:
          DATABASE_URL: postgresql://${{ secrets.POSTGRES_USER || 'user' }}:${{ secrets.POSTGRES_PASSWORD || 'password' }}@db:5432/${{ secrets.POSTGRES_DB || 'app_db' }}
        run: |
          docker compose --profile tests up -d db rabbitmq
          
          sleep 5
          
          docker compose --profile tests up --build --exit-code-from backend-tests backend-tests
